# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6aed7db6434644a375039457ae469b64408b3fdb2193a52351f83d53cccfd6f916535973b08fd59507b046994765ee348b54a432dd660263e19d9ffcee23e79

test:
  secret_key_base: e0abc77757c16af7199daddc5afa36fe822e55a039377c6782e8942da9ee69f779a663325c3ceb21b2dd4d15cf36ca6dc7a75f9b80d73c2c4b136c4218efb170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
